version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: aiplatform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 180802
    ports:
      - "5445:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"
      
  flower:
    image: mher/flower
    command: celery flower --broker=redis://redis:6379/0
    ports:
      - "5555:5555"
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379
      
volumes:
  postgres_data: